// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (typeof import.meta !== "undefined" && import.meta.env?.VITE_SUPABASE_URL) || "https://tmdkvmvpckwncmumcibt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = (typeof import.meta !== "undefined" && import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY) || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtZGt2bXZwY2t3bmNtdW1jaWJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2MzM4MzYsImV4cCI6MjA5MzIwOTgzNn0.22jxy4j5DZzbv18vlf7umColTEHWH_Jp8yNbgb71uDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const customFetch: typeof fetch = async (input, init) => {
  try {
    return await fetch(input, init);
  } catch (err) {
    // If Supabase host is unresolvable or network is offline, return synthetic 503
    // so Supabase client handles it as a normal { error } instead of an unhandled TypeError: Failed to fetch
    return new Response(
      JSON.stringify({
        message: "Supabase host unreachable or network offline",
        code: "503",
        details: "Network connection failed",
        hint: "Offline mode active",
      }),
      {
        status: 503,
        statusText: "Service Unavailable",
        headers: { "Content-Type": "application/json" },
      }
    );
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof localStorage !== "undefined" ? localStorage : undefined,
    persistSession: typeof localStorage !== "undefined",
    autoRefreshToken: typeof localStorage !== "undefined",
  },
  global: {
    fetch: customFetch,
  },
});